version: 2
references:
    # We will define reusable references here
    android_config: &android_config
      working_directory: ~/repo
      docker:
        - image: circleci/android:api-28-alpha
      environment:
        TERM: dumb
        _JAVA_OPTIONS: "-Xmx3200m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  # Build debug APK for unit tests and an instrumented test APK
  build_debug:
    <<: *android_config
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Gradle build (debug)
          command: ./gradlew -PciBuild=true :app:assembleDebug :app:assembleAndroidTest

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/

  # Run unit tests
  test_unit:
    <<: *android_config
    steps:
      - run:
          name: Run UnitTest
          command: ./gradlew testDemoDebugUnitTest

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true

      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82

      - run:
          name: Run EspressoTests
          command: ./gradlew connectedDemoDebugAndroidTest

      - store_artifacts:
          path: app/build/reports/
          destination: /reports/

      - store_test_results:
          path: app/build/test-results


workflows:
  version: 2
  workflow:
    jobs:
      - build_debug
      - test_unit

      #- test_instrumented:
       #   requires:
        #    - build_debug
      #- deploy:
       #   filters:
        #    branches:
         #     only:
          #      - master
          #requires:
           # - build_release
            #- test_unit
            #- test_instrumented