version: 2
references:
    # We will define reusable references here
    android_config: &android_config
      working_directory: ~/cubiVue/android
      docker:
        - image: circleci/android:api-28-node8-alpha
      environment:
        JVM_OPTS: -Xmx4G
        TERM: dumb # Use dumb terminal to avoid weird output from Gradle
        _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  # Build debug APK for unit tests and an instrumented test APK
  build_debug:
    <<: *android_config
    steps:
      - checkout:
          path: ~/cubiVue

      # Download and cache dependencies
      - restore_cache:
          paths:
              - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - attach_workspace:
          at: ~/cubiVue

      - run:
          name: Download Dependencies
          command: |
                   sudo chmod +x gradlew
                   ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Gradle build (debug)
          command: ./gradlew -PciBuild=true :app:assembleDebug :app:assembleAndroidTest

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: /apk/

  # Run unit tests
  test_unit:
    <<: *android_config
    steps:
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run UnitTest
          command: ./gradlew testDemoDebugUnitTest

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

  # Run UI tests
  test_instrumented:
    <<: *android_config
    steps:
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true

      - run:
          name: Wait for emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82

      - run:
          name: Run EspressoTests
          command: ./gradlew connectedDemoDebugAndroidTest

workflows:
  version: 2
  workflow:
    jobs:
      - build_debug
      - test_unit:
          requires:
            - build_debug
      - test_instrumented:
          requires:
            - build_debug